### ISSUE TITLE
Error stopping node

### ISSUE THREAD

**Issue by spady7** [Rainbow-CPaaS/node-red-contrib-ale-rainbow#2]
Hi, we are facing the following issue. Whenever I made a deploy of project (node-red Deploy) a get following error:

"Error stopping node: TypeError: rainbowSDK[instanceId].events.removeListener is not a function"

I've investigated a bit code inside ale-rainbow.js; I suppose on line 36 there is an error.
Instead of "rainbowSDK[instanceId].events.**removeListener**(handler.evt, handler.fct)" should be "rainbowSDK[instanceId].events.**on**(handler.evt, handler.fct)" ?

Let me know.
Best regards

**Comment by ArfyFR** [comment]
Hi,
I'll take the point thanks.

**Comment by ArfyFR** [comment]
Corrected in release v1.2.3
(had to manage some changes in package.json to be able to publish also to npm)
