### ISSUE TITLE
Issue room_ at ale-rainbow.js

### ISSUE THREAD

**Issue by spady7** [Rainbow-CPaaS/node-red-contrib-ale-rainbow#3]
Hi again, there is still an issue inside ale-rainbow.js.
At line 295 and 302 there is a typo and prevent to send IM to a room.
Code is:
`if (msg.payload.destJid.substring(0,4) === "room_") ...`
and
`if (node.destJid.substring(0,4) === "room_")`

Should be 

`if (msg.payload.destJid.substring(0,5) === "room_") ...`
and
`if (node.destJid.substring(0,5) === "room_")`

Regards

**Comment by ArfyFR** [comment]
Ok, thanks =)
(I also noticed a bug between the stop() and the start() I'll create)

**Comment by ArfyFR** [comment]
Corrected in v1.2.4
